#!/usr/bin/env lua

local R = require 're'

local format_pattern = R.compile [[

	segs <- {| seg* |}

	seg <- {|
		{}
		( epoch
		/ year
		/ day_long_ordinal
		/ day_short_ordinal
		/ day_long
		/ month
		/ day_short
		/ month_en_long
		/ day_en_long
		/ month_en_short
		/ day_en_short
		)
		{}
	|} / . seg

	-- 1 to 9
	day_short <-
		{~ [1-9] -> 'day_short' ~}

	-- 10 11 12
	month <-
		{~ ('1'[0-2]) -> 'month' ~}

	-- 13 to 31
	day_long <-
		{~ ('1'[3-9] / '2'%d / '3'[01]) -> 'day_long' ~}

	-- 2000 to 9999
	year <-
		{~ ([2-9]%d^3) -> 'year' ~}

	-- 10000 and above
	epoch <-
		{~ ([1-9]%d^+4) -> 'epoch' ~}

	-- day with ordinal
	day_short_ordinal <-
		{~ (day_short ordinal_suffix) -> 'day_short_ordinal' ~}

	day_long_ordinal <-
		{~ (([12]%d / '3'[01]) ordinal_suffix) -> 'day_long_ordinal' ~}

	ordinal_suffix <-
		'st' / 'nd' / 'rd' / 'th'

	-- words
	month_en_long <- {~
		( [Jj]'anuary' / [Ff]'ebruary' / [Mm]'arch' / [Aa]'pril'
		/ [Mm]'ay' / [Jj]'une' / [Jj]'uly' / [Aa]'ugust'
		/ [Ss]'eptember' / [Oo]'ctober' / [Nn]'ovember' / [Dd]'ecember'
		) -> 'month_en_long'
	~}

	month_en_short <- {~
		( [Jj]'an' / [Ff]'eb' / [Mm]'ar' / [Aa]'pr'
		/ [Mm]'ay' / [Jj]'un' / [Jj]'ul' / [Aa]'ug'
		/ [Ss]'ep' / [Oo]'ct' / [Nn]'ov' / [Dd]'ec'
		) -> 'month_en_short'
	~}

	day_en_long <- {~
		( [Ss]'unday' / [Mm]'onday' / [Tt]'uesday' / [Ww]'ednesday'
		/ [Tt]'hursday' / [Ff]'riday' / [Ss]'aturday'
		) -> 'day_en_long'
	~}

	day_en_short <- {~
		( [Ss]'un' / [Mm]'on' / [Tt]'ue' / [Ww]'ed'
		/ [Tt]'hu' / [Ff]'ri' / [Ss]'at'
		) -> 'day_en_short'
	~}

]]

-- formatters
function ordinal_en (i)
	local suffix = 'th'
	local unit = i:sub(#i)

	if #i == 1 or i:sub(#i-1,1) ~= '1' then
		if unit == '1' then
			suffix = 'st'
		elseif unit == '2' then
			suffix = 'nd'
		elseif unit == '3' then
			suffix = 'rd'
		end
	end
	return i .. suffix
end

function short_form (i)
	while #i > 1 and i:sub(1,1) == '0' do
		i = i:sub(2)
	end
	return i
end

local formatter = {
	day_en_long       = function (t) return os.date('%A', t) end,
	day_en_short      = function (t) return os.date('%a', t) end,
	day_long          = function (t) return os.date('%d', t) end,
	day_long_ordinal  = function (t) return ordinal_en(os.date('%d', t)) end,
	day_short         = function (t) return short_form(os.date('%d', t)) end,
	day_short_ordinal = function (t) return ordinal_en(short_form(os.date('%d', t))) end,
	epoch             = function (t) return os.date('%s', t) end,
	month_en_long     = function (t) return os.date('%B', t) end,
	month_en_short    = function (t) return os.date('%b', t) end,
	month             = function (t) return os.date('%m', t) end,
	year              = function (t) return os.date('%Y', t) end,
}

-- main
local input = table.concat(arg, ' ')
local parsed = format_pattern:match(input)

-- print((require'cjson').encode({input=input,parsed=parsed}))os.exit()

while true do
	local d = io.read()
	if d == nil then break end

	local t = os.time{
		year = 0 + d:sub(1, 4),
		month = 0 + d:sub(6, 7),
		day = 0 + d:sub(9, 10),
	}

	local out = {}
	local cur = 1

	for _, seg in ipairs(parsed) do
		if cur < seg[1] then
			out[#out+1] = input:sub(cur, seg[1]-1)
		end

		out[#out+1] = formatter[seg[2]](t)

		cur = seg[3]
	end
	if cur < #input-1 then
		out[#out+1] = input:sub(cur, #input)
	end
	print(table.concat(out))
end
