#!/usr/bin/env lua

local R = require 're'
local J = require 'cjson'

local format_pattern = R.compile [[

	segs <- {| seg* |}

	seg <- {|
		{}
		( epoch 
		/ year 
		/ day_long_ordinal 
		/ day_short_ordinal 
		/ day_long 
		/ month 
		/ day_short

		/ month_en_long
		/ day_en_long
		/ month_en_short
		/ day_en_short
		)
		{}
	|} / . seg

	-- 1 to 9
	day_short <-
		{~ [1-9] -> 'day_short' ~}

	-- 10 11 12
	month <-
		{~ ('1'[0-2]) -> 'month' ~}

	-- 13 to 31
	day_long <-
		{~ ('1'[3-9] / '2'%d / '3'[01]) -> 'day_long' ~}

	-- 2000 to 9999
	year <-
		{~ ([2-9]%d^3) -> 'year' ~}

	-- 10000 and above
	epoch <-
		{~ ([1-9]%d^+4) -> 'epoch' ~}

	-- day with ordinal
	day_short_ordinal <-
		{~ (day_short ordinal_suffix) -> 'day_short_ordinal' ~}

	day_long_ordinal <-
		{~ (([12]%d / '3'[01]) ordinal_suffix) -> 'day_long_ordinal' ~}

	ordinal_suffix <-
		'st' / 'nd' / 'rd' / 'th'

	month_en_long <- {~
		( [Jj]'anuary'
		/ [Ff]'ebruary'
		/ [Mm]'arch'
		/ [Aa]'pril'
		/ [Mm]'ay'
		/ [Jj]'une'
		/ [Jj]'uly'
		/ [Aa]'ugust'
		/ [Ss]'eptember'
		/ [Oo]'ctober'
		/ [Nn]'ovember'
		/ [Dd]'ecember'
		) -> 'month_en_long'
	~}

	month_en_short <- {~
		( [Jj]'an'
		/ [Ff]'eb'
		/ [Mm]'ar'
		/ [Aa]'pr'
		/ [Mm]'ay'
		/ [Jj]'un'
		/ [Jj]'ul'
		/ [Aa]'ug'
		/ [Ss]'ep'
		/ [Oo]'ct'
		/ [Nn]'ov'
		/ [Dd]'ec'
		) -> 'month_en_short'
	~}

	day_en_long <- {~
		( [Ss]'unday'
		/ [Mm]'onday'
		/ [Tt]'uesday'
		/ [Ww]'ednesday'
		/ [Tt]'hursday'
		/ [Ff]'riday'
		/ [Ss]'aturday'
		) -> 'day_en_long'
	~}

	day_en_short <- {~
		( [Ss]'un'
		/ [Mm]'on'
		/ [Tt]'ue'
		/ [Ww]'ed'
		/ [Tt]'hu'
		/ [Ff]'ri'
		/ [Ss]'at'
		) -> 'day_en_short'
	~}
]]

local input = table.concat(arg, ' ')
local match = format_pattern:match(input)

print(J.encode(match))
