#!/usr/bin/env lua

if #arg == 0 then
	io.stderr:write('Usage: lines modulus val val ...\n')
	os.exit(1)
end

local mod = 0 + arg[1]
local l = 1

for line in io.lines() do
	for i = 2, #arg do
		if (l - arg[i]) % mod == 0 then
			print(line)
		end
	end
	l = l + 1
end

